### ISSUE TITLE
Display error in bash on windows

### ISSUE THREAD

**Issue by rmreq** [santagada/xontrib-powerline#12]
When using WSL the prompt and status bar aren't displayed correctly. Rather than modifying the color of the relevant characters, the color code strings are displayed:

![powerline](https://cloud.githubusercontent.com/assets/28678557/26429173/1dd54fca-40ab-11e7-98ef-3d132d0f5f38.PNG)
Note: the last line is the prompt, after loading the plugin.

Any ideas about what's causing this?
The same issue appears when I use the WSL standard terminal, as well as others like HyperTerm

**Comment by santagada** [comment]
no idea, maybe asking on xonsh gitter might help https://gitter.im/xonsh/xonsh, it might be related to readline/prompt-toolkit differences maybe.

**Comment by santagada** [comment]
@rmreq can you give me the value of your $PROMPT variable before loading powerline?

**Comment by rmreq** [comment]
Thanks, but it appears to be working now. I was using the Hyper terminal emulator, which seems to have a ton of display errors that mysteriously come and go. I suspect that was the cause.
