### ISSUE TITLE
Colors are not being rendered correctly

### ISSUE THREAD

**Issue by AngellusMortis** [santagada/xontrib-powerline#17]
I am seeing the raw formatting codes instead of the rendered colors.

![image](https://user-images.githubusercontent.com/490848/39205532-e986a7ca-47c8-11e8-80c0-a7ff0f08adc8.png)

This only happens when I use Powerline inside of Xonsh via ```xontrib load powerline```. If I run Powerline manually with bash, the issue does not occur.

**Comment by bestlem** [comment]
What terminal are you using and how is it configured? e.g. what terminal does it emulate?
What does ${...} show?
