### ISSUE TITLE
Bottom prompt is messed up by ptk2

### ISSUE THREAD

**Issue by bestlem** [santagada/xontrib-powerline#18]
Xonsh not uses prompt-toolkit 2. This seems to mess up the colours and the arrows on the bottom prompt. I think this is because ptk2 by default reverses the colours that it is given in xonsh's $BOTTOM_TOOLBAR

I have a hack in https://github.com/bestlem/xontrib-powerline I also changed some of the hard coded colours to match my dark background. I could not work out the correct wt as something changes $BLUE to $ansiblue etc and I can see how to add reverse into that.

**Comment by laloch** [comment]
Hi @bestlem, since v0.8.0 xonsh supports `$PTK_STYLE_OVERRIDES` environment variable. You may want to add
```
$PTK_STYLE_OVERRIDES['bottom-toolbar'] = 'noreverse'
```
to your xonshrc.
