### ISSUE TITLE
Updated version in pip

### ISSUE THREAD

**Issue by tiagofassoni** [santagada/xontrib-powerline#4]
The version on pip wasn't updated, so I'm still getting deprecation warnings.

**Comment by santagada** [comment]
Yes I didn't update it yet. Sorry I can only do this next week, if someone wants to do it before them I can add you as a contributor on pypi for this week at least so you can push master to it.

**Comment by tiagofassoni** [comment]
Please add me as a contributor, then.

Thanks!

Em 13 de fev de 2017 1:13 PM, "Leonardo Santagada" <notifications@github.com>
escreveu:

Yes I didn't update it yet. Sorry I can only do this next week, if someone
wants to do it before them I can add you as a contributor on pypi for this
week at least so you can push master to it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/santagada/xontrib-powerline/issues/4#issuecomment-279419646>,
or mute the thread

**Comment by nvander1** [comment]
The deprecation warning is still there as of today.

**Comment by santagada** [comment]
released a new version, please reopen if the bug persist
