### ISSUE TITLE
Can you include a Right Prompt besides the Left Prompt

### ISSUE THREAD

**Issue by SolarAquarion** [santagada/xontrib-powerline#7]

**Comment by santagada** [comment]
- Do you have specific things you want to have in the right prompt? I'm planning to implement it only when I implement right facing prompts... so maybe you have any specific requests it can go in together with that.

**Comment by SolarAquarion** [comment]
Time

**Comment by SolarAquarion** [comment]
https://github.com/bhilburn/powerlevel9k#available-prompt-segments

**Comment by santagada** [comment]
https://github.com/santagada/xontrib-powerline/releases/tag/v0.3.0 done, and by default we have a clock to the right.
