### ISSUE TITLE
environment variable $HOME missing on windows

### ISSUE THREAD

**Issue by sejktmcsdlmfhsc** [santagada/xontrib-powerline#9]
@santagada I was so exited on my xonsh powerline setup at home, that I tried to migrate it to my win box at work. It turned out that was actually simple: the only one thing missing for it to work on that system was the environment variable $HOME.
I quickly patched it in my .xonshrc with the two lines below. 
I am not sure though, if that would be a xontrib-powerline or rather a xonsh fix?
```python
import os
$HOME=os.path.expanduser("~")
```

**Comment by santagada** [comment]
I think this is mostly for XONSH, I'm impressed it doesn't support it by default, can you open a ticket on xonsh and link to this so we can track it?

If I get time I will add this inside powerline for now, but it really shouldn't be my responsability.

**Comment by sejktmcsdlmfhsc** [comment]
I agree should probably added in xonsh itself, 
once it is there, then there would be no need 
for adding it in xontrib powerline
Sure:
https://github.com/xonsh/xonsh/issues/2334

**Comment by santagada** [comment]
version 0.3.3 hopefully fixes this.
